# 00. Tensorflow Fundamentals Exercises

In [1]:
!nvidia-smi

Sat Jun 18 18:08:36 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.96       Driver Version: 512.96       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   53C    P8     6W /  N/A |   4438MiB /  6144MiB |     29%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.9.1'

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [5]:
scalar = tf.constant(3)
vector = tf.constant([3,4])
matrix = tf.constant(np.random.randint(0, 100, size = 12).reshape(3,4))
tensor = tf.constant(np.random.randint(0, 10, 120).reshape(2,3,4,5))
scalar.shape, vector.shape, matrix.shape, tensor.shape

(TensorShape([]),
 TensorShape([2]),
 TensorShape([3, 4]),
 TensorShape([2, 3, 4, 5]))

## 2. Find the shape, rank and size of the tensors you created in 1.

In [6]:
def get_tensor_attributes(tensor):
    print(f"The shape of the tensor: {tensor.shape}")
    print(f"The rank of the tensor: {tensor.ndim}")
    print(f"The size of the tensor: {tf.size(tensor)}")

get_tensor_attributes(scalar)
print("#"*80)
get_tensor_attributes(vector)
print("#"*80)
get_tensor_attributes(matrix)
print("#"*80)
get_tensor_attributes(tensor)

The shape of the tensor: ()
The rank of the tensor: 0
The size of the tensor: 1
################################################################################
The shape of the tensor: (2,)
The rank of the tensor: 1
The size of the tensor: 2
################################################################################
The shape of the tensor: (3, 4)
The rank of the tensor: 2
The size of the tensor: 12
################################################################################
The shape of the tensor: (2, 3, 4, 5)
The rank of the tensor: 4
The size of the tensor: 120


## 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [9]:
A = tf.random.uniform((5,300), 0, 1)
B = tf.random.normal((5, 300),0, 1)
A.shape, B.shape,tf.reduce_min(A), tf.reduce_max(A)

(TensorShape([5, 300]),
 TensorShape([5, 300]),
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0663948e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9995432>)

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [11]:
tf.matmul(tf.transpose(A), B).shape, tf.matmul(A, tf.transpose(B)).shape # can use tf.reshape also

(TensorShape([300, 300]), TensorShape([5, 5]))

## 5. Multiply the two tensors you created in 3 using dot product.

In [12]:
tf.tensordot(tf.transpose(A), B, axes = 1).shape, tf.tensordot(A, tf.transpose(B), axes = 1).shape

(TensorShape([300, 300]), TensorShape([5, 5]))

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [14]:
C = tf.random.uniform((224,224,3), 0, 1)
C.shape

TensorShape([224, 224, 3])

## 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [17]:
tf.reduce_max(C, axis = 1), tf.reduce_min(C, axis = 1)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[0.99929464, 0.99847305, 0.99600554],
        [0.99632215, 0.9991636 , 0.99711037],
        [0.99543357, 0.9922451 , 0.9930996 ],
        [0.99597156, 0.9983555 , 0.9998143 ],
        [0.99721885, 0.9885218 , 0.9974985 ],
        [0.9982543 , 0.98510695, 0.9851965 ],
        [0.99455345, 0.99412894, 0.99547505],
        [0.9885986 , 0.9935937 , 0.99498534],
        [0.9992198 , 0.99710596, 0.99553597],
        [0.9947766 , 0.9998331 , 0.999136  ],
        [0.99804854, 0.992869  , 0.991797  ],
        [0.99803114, 0.9996486 , 0.99635696],
        [0.99579704, 0.9985244 , 0.99988043],
        [0.99955404, 0.99549866, 0.9931942 ],
        [0.99349916, 0.98829603, 0.9935293 ],
        [0.9996127 , 0.99889195, 0.99670696],
        [0.99897337, 0.9985746 , 0.9967694 ],
        [0.99742806, 0.99355745, 0.9999821 ],
        [0.9975823 , 0.99781287, 0.9939314 ],
        [0.99627745, 0.9981507 , 0.98471344],
        [0.99026954, 0.998167

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [18]:
D = tf.random.normal((1,224,224,3))
D.shape, tf.squeeze(D).shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [21]:
E = tf.constant(np.arange(1, 11))

## 10. One-hot encode the tensor you created in 9.

In [22]:
tf.one_hot(E, depth = tf.convert_to_tensor(tf.unique(E)).shape[1])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>